version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/uploaded_files:/app/uploaded_files
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
